### ISSUE TITLE
build后点击登录按钮没有跳转到dashboard界面

### ISSUE THREAD

**Issue by kanyuanzhi** [windyao/proton-admin#1]
你好作者，我把你的项目打包点击登录按钮跳转不到dashboard界面是什么原因？后台搭了跨域服务器，可以正确处理login，然后界面就一直停在登录，开发环境下没问题。

**Comment by windyao** [comment]
> 你好作者，我把你的项目打包点击登录按钮跳转不到dashboard界面是什么原因？后台搭了跨域服务器，可以正确处理login，然后界面就一直停在登录，开发环境下没问题。

您好，这个问题是这样的：Vue Element Admin使用了js-cookie来进行cookie的操作，在dev环境下可以正常读写cookie，而在打包后就无法操作cookie了。目前我的做法是使用localstorage替换cookie。

在我其他的项目中，使用了SSO登录，cookie是由服务端写入的，所以没有这个问题。不知道您具体的登录模式是什么。

我更新了代码，您可以重新下载试试。

谢谢。

**Comment by windyao** [comment]
> 你好作者，我把你的项目打包点击登录按钮跳转不到dashboard界面是什么原因？后台搭了跨域服务器，可以正确处理login，然后界面就一直停在登录，开发环境下没问题。

您好，我改变了做法，不再使用localstorage来替代cookie，而是使用electron-cookies来支持。
您可以更新这个项目，或者在本地项目中：

npm install heap/electron-cookies

然后在src/renderer/main.js中
require('electron-cookies');

就可以了。

**Comment by kanyuanzhi** [comment]
感谢！当时我已经改成sessionstorage然后解决了这个问题，所以就没有再关注这个issue了，现在才看到，很详细，谢谢！
